// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/sync/queue/sync_operation.dart';
import 'features/rooms/domain/models/room_entity.dart';
import 'features/sync/domain/models/sync_queue_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6745416085832758094),
    name: 'SyncOperation',
    lastPropertyId: const obx_int.IdUid(8, 3989951310260973183),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3544283257060899409),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3546777937683684690),
        name: 'entityType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6906847438066707951),
        name: 'entityId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 4360261565738537259),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7607434057992922833),
        name: 'operationType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6903794808878611245),
        name: 'payload',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 746291391528632149),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3147309187764938428),
        name: 'retryCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3989951310260973183),
        name: 'status',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 7620158859322961069),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4713810608890448517),
    name: 'RoomEntity',
    lastPropertyId: const obx_int.IdUid(7, 7596923131156569766),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4517471256846531402),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8316242147467889495),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 5571832571850040683),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7663083862143678281),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3423909967570567187),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7466888729255366679),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 50749940883394103),
        name: 'pricePerNight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7596923131156569766),
        name: 'lastModifiedHlc',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1555509189638963268),
    name: 'SyncQueueEntity',
    lastPropertyId: const obx_int.IdUid(8, 7331648130451764623),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1878886669847972723),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4867101220748482666),
        name: 'entityType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4763573936787682385),
        name: 'entityId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8495670056425771149),
        name: 'operation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8748174432563745490),
        name: 'payload',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5328232975510807314),
        name: 'hlcTimestamp',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6071884653774100936),
        name: 'status',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7331648130451764623),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 1555509189638963268),
    lastIndexId: const obx_int.IdUid(3, 5571832571850040683),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    SyncOperation: obx_int.EntityDefinition<SyncOperation>(
      model: _entities[0],
      toOneRelations: (SyncOperation object) => [],
      toManyRelations: (SyncOperation object) => {},
      getId: (SyncOperation object) => object.id,
      setId: (SyncOperation object, int id) {
        object.id = id;
      },
      objectToFB: (SyncOperation object, fb.Builder fbb) {
        final entityTypeOffset = fbb.writeString(object.entityType);
        final entityIdOffset = fbb.writeString(object.entityId);
        final operationTypeOffset = fbb.writeString(object.operationType);
        final payloadOffset = fbb.writeString(object.payload);
        final statusOffset = fbb.writeString(object.status);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, entityTypeOffset);
        fbb.addOffset(2, entityIdOffset);
        fbb.addOffset(3, operationTypeOffset);
        fbb.addOffset(4, payloadOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.retryCount);
        fbb.addOffset(7, statusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final entityTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final entityIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final operationTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final payloadParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final retryCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final object = SyncOperation(
          id: idParam,
          entityType: entityTypeParam,
          entityId: entityIdParam,
          operationType: operationTypeParam,
          payload: payloadParam,
          createdAt: createdAtParam,
          retryCount: retryCountParam,
          status: statusParam,
        );

        return object;
      },
    ),
    RoomEntity: obx_int.EntityDefinition<RoomEntity>(
      model: _entities[1],
      toOneRelations: (RoomEntity object) => [],
      toManyRelations: (RoomEntity object) => {},
      getId: (RoomEntity object) => object.id,
      setId: (RoomEntity object, int id) {
        object.id = id;
      },
      objectToFB: (RoomEntity object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final typeOffset = fbb.writeString(object.type);
        final statusOffset = fbb.writeString(object.status);
        final lastModifiedHlcOffset = fbb.writeString(object.lastModifiedHlc);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, typeOffset);
        fbb.addOffset(4, statusOffset);
        fbb.addFloat64(5, object.pricePerNight);
        fbb.addOffset(6, lastModifiedHlcOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final pricePerNightParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final lastModifiedHlcParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final object = RoomEntity(
          id: idParam,
          uuid: uuidParam,
          name: nameParam,
          type: typeParam,
          status: statusParam,
          pricePerNight: pricePerNightParam,
          lastModifiedHlc: lastModifiedHlcParam,
        );

        return object;
      },
    ),
    SyncQueueEntity: obx_int.EntityDefinition<SyncQueueEntity>(
      model: _entities[2],
      toOneRelations: (SyncQueueEntity object) => [],
      toManyRelations: (SyncQueueEntity object) => {},
      getId: (SyncQueueEntity object) => object.id,
      setId: (SyncQueueEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SyncQueueEntity object, fb.Builder fbb) {
        final entityTypeOffset = fbb.writeString(object.entityType);
        final operationOffset = fbb.writeString(object.operation);
        final payloadOffset = fbb.writeString(object.payload);
        final hlcTimestampOffset = fbb.writeString(object.hlcTimestamp);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, entityTypeOffset);
        fbb.addInt64(2, object.entityId);
        fbb.addOffset(3, operationOffset);
        fbb.addOffset(4, payloadOffset);
        fbb.addOffset(5, hlcTimestampOffset);
        fbb.addInt64(6, object.status);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final entityTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final entityIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final operationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final payloadParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final hlcTimestampParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final statusParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final object = SyncQueueEntity(
          id: idParam,
          entityType: entityTypeParam,
          entityId: entityIdParam,
          operation: operationParam,
          payload: payloadParam,
          hlcTimestamp: hlcTimestampParam,
          status: statusParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SyncOperation] entity fields to define ObjectBox queries.
class SyncOperation_ {
  /// See [SyncOperation.id].
  static final id = obx.QueryIntegerProperty<SyncOperation>(
    _entities[0].properties[0],
  );

  /// See [SyncOperation.entityType].
  static final entityType = obx.QueryStringProperty<SyncOperation>(
    _entities[0].properties[1],
  );

  /// See [SyncOperation.entityId].
  static final entityId = obx.QueryStringProperty<SyncOperation>(
    _entities[0].properties[2],
  );

  /// See [SyncOperation.operationType].
  static final operationType = obx.QueryStringProperty<SyncOperation>(
    _entities[0].properties[3],
  );

  /// See [SyncOperation.payload].
  static final payload = obx.QueryStringProperty<SyncOperation>(
    _entities[0].properties[4],
  );

  /// See [SyncOperation.createdAt].
  static final createdAt = obx.QueryDateProperty<SyncOperation>(
    _entities[0].properties[5],
  );

  /// See [SyncOperation.retryCount].
  static final retryCount = obx.QueryIntegerProperty<SyncOperation>(
    _entities[0].properties[6],
  );

  /// See [SyncOperation.status].
  static final status = obx.QueryStringProperty<SyncOperation>(
    _entities[0].properties[7],
  );
}

/// [RoomEntity] entity fields to define ObjectBox queries.
class RoomEntity_ {
  /// See [RoomEntity.id].
  static final id = obx.QueryIntegerProperty<RoomEntity>(
    _entities[1].properties[0],
  );

  /// See [RoomEntity.uuid].
  static final uuid = obx.QueryStringProperty<RoomEntity>(
    _entities[1].properties[1],
  );

  /// See [RoomEntity.name].
  static final name = obx.QueryStringProperty<RoomEntity>(
    _entities[1].properties[2],
  );

  /// See [RoomEntity.type].
  static final type = obx.QueryStringProperty<RoomEntity>(
    _entities[1].properties[3],
  );

  /// See [RoomEntity.status].
  static final status = obx.QueryStringProperty<RoomEntity>(
    _entities[1].properties[4],
  );

  /// See [RoomEntity.pricePerNight].
  static final pricePerNight = obx.QueryDoubleProperty<RoomEntity>(
    _entities[1].properties[5],
  );

  /// See [RoomEntity.lastModifiedHlc].
  static final lastModifiedHlc = obx.QueryStringProperty<RoomEntity>(
    _entities[1].properties[6],
  );
}

/// [SyncQueueEntity] entity fields to define ObjectBox queries.
class SyncQueueEntity_ {
  /// See [SyncQueueEntity.id].
  static final id = obx.QueryIntegerProperty<SyncQueueEntity>(
    _entities[2].properties[0],
  );

  /// See [SyncQueueEntity.entityType].
  static final entityType = obx.QueryStringProperty<SyncQueueEntity>(
    _entities[2].properties[1],
  );

  /// See [SyncQueueEntity.entityId].
  static final entityId = obx.QueryIntegerProperty<SyncQueueEntity>(
    _entities[2].properties[2],
  );

  /// See [SyncQueueEntity.operation].
  static final operation = obx.QueryStringProperty<SyncQueueEntity>(
    _entities[2].properties[3],
  );

  /// See [SyncQueueEntity.payload].
  static final payload = obx.QueryStringProperty<SyncQueueEntity>(
    _entities[2].properties[4],
  );

  /// See [SyncQueueEntity.hlcTimestamp].
  static final hlcTimestamp = obx.QueryStringProperty<SyncQueueEntity>(
    _entities[2].properties[5],
  );

  /// See [SyncQueueEntity.status].
  static final status = obx.QueryIntegerProperty<SyncQueueEntity>(
    _entities[2].properties[6],
  );

  /// See [SyncQueueEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<SyncQueueEntity>(
    _entities[2].properties[7],
  );
}
