// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/sync/queue/sync_operation.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6745416085832758094),
    name: 'SyncOperation',
    lastPropertyId: const obx_int.IdUid(8, 3989951310260973183),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3544283257060899409),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3546777937683684690),
        name: 'entityType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6906847438066707951),
        name: 'entityId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 4360261565738537259),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7607434057992922833),
        name: 'operationType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6903794808878611245),
        name: 'payload',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 746291391528632149),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3147309187764938428),
        name: 'retryCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3989951310260973183),
        name: 'status',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 7620158859322961069),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 6745416085832758094),
    lastIndexId: const obx_int.IdUid(2, 7620158859322961069),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    SyncOperation: obx_int.EntityDefinition<SyncOperation>(
      model: _entities[0],
      toOneRelations: (SyncOperation object) => [],
      toManyRelations: (SyncOperation object) => {},
      getId: (SyncOperation object) => object.id,
      setId: (SyncOperation object, int id) {
        object.id = id;
      },
      objectToFB: (SyncOperation object, fb.Builder fbb) {
        final entityTypeOffset = fbb.writeString(object.entityType);
        final entityIdOffset = fbb.writeString(object.entityId);
        final operationTypeOffset = fbb.writeString(object.operationType);
        final payloadOffset = fbb.writeString(object.payload);
        final statusOffset = fbb.writeString(object.status);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, entityTypeOffset);
        fbb.addOffset(2, entityIdOffset);
        fbb.addOffset(3, operationTypeOffset);
        fbb.addOffset(4, payloadOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.retryCount);
        fbb.addOffset(7, statusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final entityTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final entityIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final operationTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final payloadParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final retryCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final object = SyncOperation(
          id: idParam,
          entityType: entityTypeParam,
          entityId: entityIdParam,
          operationType: operationTypeParam,
          payload: payloadParam,
          createdAt: createdAtParam,
          retryCount: retryCountParam,
          status: statusParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SyncOperation] entity fields to define ObjectBox queries.
class SyncOperation_ {
  /// See [SyncOperation.id].
  static final id = obx.QueryIntegerProperty<SyncOperation>(
    _entities[0].properties[0],
  );

  /// See [SyncOperation.entityType].
  static final entityType = obx.QueryStringProperty<SyncOperation>(
    _entities[0].properties[1],
  );

  /// See [SyncOperation.entityId].
  static final entityId = obx.QueryStringProperty<SyncOperation>(
    _entities[0].properties[2],
  );

  /// See [SyncOperation.operationType].
  static final operationType = obx.QueryStringProperty<SyncOperation>(
    _entities[0].properties[3],
  );

  /// See [SyncOperation.payload].
  static final payload = obx.QueryStringProperty<SyncOperation>(
    _entities[0].properties[4],
  );

  /// See [SyncOperation.createdAt].
  static final createdAt = obx.QueryDateProperty<SyncOperation>(
    _entities[0].properties[5],
  );

  /// See [SyncOperation.retryCount].
  static final retryCount = obx.QueryIntegerProperty<SyncOperation>(
    _entities[0].properties[6],
  );

  /// See [SyncOperation.status].
  static final status = obx.QueryStringProperty<SyncOperation>(
    _entities[0].properties[7],
  );
}
