"""Init Schema

Revision ID: 45118686c0b4
Revises: 
Create Date: 2026-07-12 19:49:39.770860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45118686c0b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('guest_id', name=op.f('pk_guests'))
    )
    op.create_index(op.f('ix_guests_last_modified_hlc'), 'guests', ['last_modified_hlc'], unique=False)
    op.create_table('owners',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('mobile_verified', sa.Boolean(), nullable=False),
    sa.Column('alternate_contact', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('selfie_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('owner_id', name=op.f('pk_owners')),
    sa.UniqueConstraint('email', name=op.f('uq_owners_email')),
    sa.UniqueConstraint('mobile_number', name=op.f('uq_owners_mobile_number'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('permission_code', sa.String(length=60), nullable=False),
    sa.Column('module_name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('permission_code', name=op.f('uq_permissions_permission_code'))
    )
    op.create_table('businesses',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('business_type', sa.String(length=30), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_reg_number', sa.String(length=50), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('gst_certificate_url', sa.Text(), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], name=op.f('fk_businesses_owner_id_owners')),
    sa.PrimaryKeyConstraint('business_id', name=op.f('pk_businesses'))
    )
    op.create_table('properties',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('property_name', sa.String(length=200), nullable=False),
    sa.Column('property_type', sa.String(length=30), nullable=True),
    sa.Column('star_category', sa.SmallInteger(), nullable=True),
    sa.Column('year_established', sa.SmallInteger(), nullable=True),
    sa.Column('total_floors', sa.SmallInteger(), nullable=True),
    sa.Column('total_rooms', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_device_id', sa.UUID(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=15), nullable=True),
    sa.Column('onboarding_status', sa.String(length=20), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], name=op.f('fk_properties_business_id_businesses')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], name=op.f('fk_properties_owner_id_owners')),
    sa.PrimaryKeyConstraint('property_id', name=op.f('pk_properties'))
    )
    op.create_index(op.f('ix_properties_last_modified_hlc'), 'properties', ['last_modified_hlc'], unique=False)
    op.create_table('daily_kpi_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('occupied_rooms', sa.Integer(), nullable=False),
    sa.Column('vacant_rooms', sa.Integer(), nullable=False),
    sa.Column('revenue_room_rent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('revenue_addons', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expenses_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding_payments', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_collected', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_daily_kpi_snapshots_property_id_properties')),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_daily_kpi_snapshots')),
    sa.UniqueConstraint('property_id', 'snapshot_date', name='uq_daily_kpi_property_date'),
    sa.UniqueConstraint('property_id', 'snapshot_date', name='uq_daily_kpi_property_date')
    )
    op.create_index(op.f('ix_daily_kpi_snapshots_property_id'), 'daily_kpi_snapshots', ['property_id'], unique=False)
    op.create_table('pending_dues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('reminder_status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_pending_dues_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_dues'))
    )
    op.create_table('report_templates',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('report_name', sa.String(length=150), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('configuration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_report_templates_property_id_properties')),
    sa.PrimaryKeyConstraint('template_id', name=op.f('pk_report_templates'))
    )
    op.create_index(op.f('ix_report_templates_property_id'), 'report_templates', ['property_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('role_code', sa.String(length=40), nullable=False),
    sa.Column('role_name', sa.String(length=80), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_roles_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('property_id', 'role_code', name='uq_roles_property_role_code')
    )
    op.create_table('room_categories',
    sa.Column('room_category_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=True),
    sa.Column('number_of_rooms', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_room_categories_property_id_properties')),
    sa.PrimaryKeyConstraint('room_category_id', name=op.f('pk_room_categories'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('license_id', sa.String(length=100), nullable=True),
    sa.Column('device_limit', sa.Integer(), nullable=False),
    sa.Column('registered_devices', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_subscriptions_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('license_id', name=op.f('uq_subscriptions_license_id'))
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('room_category_id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('housekeeping_status', sa.String(length=20), nullable=True),
    sa.Column('occupancy_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_category_id'], ['room_categories.room_category_id'], name=op.f('fk_rooms_room_category_id_room_categories')),
    sa.PrimaryKeyConstraint('room_id', name=op.f('pk_rooms'))
    )
    op.create_index(op.f('ix_rooms_last_modified_hlc'), 'rooms', ['last_modified_hlc'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('recipient_role', sa.String(length=40), nullable=False),
    sa.Column('delivery_channel', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.template_id'], name=op.f('fk_scheduled_reports_template_id_report_templates')),
    sa.PrimaryKeyConstraint('schedule_id', name=op.f('pk_scheduled_reports'))
    )
    op.create_index(op.f('ix_scheduled_reports_template_id'), 'scheduled_reports', ['template_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('biometric_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_primary_owner', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failed_login_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_pending_sync', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_users_property_id_properties')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_last_modified_hlc'), 'users', ['last_modified_hlc'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('target_entity', sa.String(length=50), nullable=True),
    sa.Column('target_record_id', sa.UUID(), nullable=True),
    sa.Column('old_value_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('previous_log_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_audit_logs_property_id_properties')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_module_name'), 'audit_logs', ['module_name'], unique=False)
    op.create_index('ix_audit_logs_property_timestamp', 'audit_logs', ['property_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_entity', 'target_record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('booking_type', sa.String(length=20), nullable=True),
    sa.Column('booking_source', sa.String(length=30), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('room_rent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_payable', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('advance_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pending_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('booking_status', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_bookings_guest_id_guests')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_bookings_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_bookings_room_id_rooms')),
    sa.PrimaryKeyConstraint('booking_id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_last_modified_hlc'), 'bookings', ['last_modified_hlc'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_uid', sa.String(length=128), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('primary_user_id', sa.UUID(), nullable=True),
    sa.Column('device_name', sa.String(length=80), nullable=True),
    sa.Column('os_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_user_id'], ['users.id'], name=op.f('fk_devices_primary_user_id_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_devices_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('device_uid', name=op.f('uq_devices_device_uid'))
    )
    op.create_table('housekeeping_tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('checklist_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], name=op.f('fk_housekeeping_tasks_assigned_staff_id_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_housekeeping_tasks_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_housekeeping_tasks_room_id_rooms')),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_housekeeping_tasks'))
    )
    op.create_index(op.f('ix_housekeeping_tasks_last_modified_hlc'), 'housekeeping_tasks', ['last_modified_hlc'], unique=False)
    op.create_table('lost_and_found',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('found_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['found_by'], ['users.id'], name=op.f('fk_lost_and_found_found_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_lost_and_found_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_lost_and_found_room_id_rooms')),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_lost_and_found'))
    )
    op.create_table('maintenance_tickets',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_maintenance_tickets_assigned_to_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_maintenance_tickets_property_id_properties')),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_maintenance_tickets_reported_by_users')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_maintenance_tickets_room_id_rooms')),
    sa.PrimaryKeyConstraint('ticket_id', name=op.f('pk_maintenance_tickets'))
    )
    op.create_index(op.f('ix_maintenance_tickets_last_modified_hlc'), 'maintenance_tickets', ['last_modified_hlc'], unique=False)
    op.create_table('property_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_property_settings_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_property_settings_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_settings'))
    )
    op.create_index(op.f('ix_property_settings_last_modified_hlc'), 'property_settings', ['last_modified_hlc'], unique=False)
    op.create_index(op.f('ix_property_settings_property_id'), 'property_settings', ['property_id'], unique=False)
    op.create_index('uq_property_settings_active_key', 'property_settings', ['property_id', 'setting_key'], unique=True, postgresql_where=sa.text('is_deleted = FALSE'), sqlite_where=sa.text('is_deleted = FALSE'))
    op.create_table('system_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_system_configurations_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_configurations'))
    )
    op.create_index(op.f('ix_system_configurations_config_key'), 'system_configurations', ['config_key'], unique=True)
    op.create_table('check_ins',
    sa.Column('checkin_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('advance_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id_verified', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_check_ins_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_check_ins_guest_id_guests')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_check_ins_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_check_ins_room_id_rooms')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_check_ins_staff_id_users')),
    sa.PrimaryKeyConstraint('checkin_id', name=op.f('pk_check_ins'))
    )
    op.create_index(op.f('ix_check_ins_last_modified_hlc'), 'check_ins', ['last_modified_hlc'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_invoices_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_invoices_guest_id_guests')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_invoices_property_id_properties')),
    sa.PrimaryKeyConstraint('invoice_id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_invoices_invoice_number'))
    )
    op.create_table('room_assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_room_assignments_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_room_assignments_guest_id_guests')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_room_assignments_room_id_rooms')),
    sa.PrimaryKeyConstraint('assignment_id', name=op.f('pk_room_assignments'))
    )
    op.create_table('check_outs',
    sa.Column('checkout_id', sa.UUID(), nullable=False),
    sa.Column('checkin_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('checkout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('advance_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remaining_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('checkout_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_check_outs_booking_id_bookings')),
    sa.ForeignKeyConstraint(['checkin_id'], ['check_ins.checkin_id'], name=op.f('fk_check_outs_checkin_id_check_ins')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_check_outs_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_check_outs_room_id_rooms')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_check_outs_staff_id_users')),
    sa.PrimaryKeyConstraint('checkout_id', name=op.f('pk_check_outs'))
    )
    op.create_index(op.f('ix_check_outs_last_modified_hlc'), 'check_outs', ['last_modified_hlc'], unique=False)
    op.create_table('invoice_items',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], name=op.f('fk_invoice_items_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_invoice_items'))
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('payment_mode', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_payments_booking_id_bookings')),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], name=op.f('fk_payments_collected_by_users')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], name=op.f('fk_payments_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_payments')),
    sa.UniqueConstraint('transaction_id', name=op.f('uq_payments_transaction_id'))
    )
    op.create_index(op.f('ix_payments_last_modified_hlc'), 'payments', ['last_modified_hlc'], unique=False)
    op.create_table('subscription_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bank_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], name=op.f('fk_subscription_transactions_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_subscription_transactions_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_transactions')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_subscription_transactions_payment_id'))
    )
    op.create_table('payment_transactions',
    sa.Column('txn_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], name=op.f('fk_payment_transactions_payment_id_payments')),
    sa.PrimaryKeyConstraint('txn_id', name=op.f('pk_payment_transactions'))
    )
    op.create_table('split_payments',
    sa.Column('split_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], name=op.f('fk_split_payments_payment_id_payments')),
    sa.PrimaryKeyConstraint('split_id', name=op.f('pk_split_payments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('split_payments')
    op.drop_table('payment_transactions')
    op.drop_table('subscription_transactions')
    op.drop_index(op.f('ix_payments_last_modified_hlc'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_check_outs_last_modified_hlc'), table_name='check_outs')
    op.drop_table('check_outs')
    op.drop_table('room_assignments')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_check_ins_last_modified_hlc'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_system_configurations_config_key'), table_name='system_configurations')
    op.drop_table('system_configurations')
    op.drop_index('uq_property_settings_active_key', table_name='property_settings', postgresql_where=sa.text('is_deleted = FALSE'), sqlite_where=sa.text('is_deleted = FALSE'))
    op.drop_index(op.f('ix_property_settings_property_id'), table_name='property_settings')
    op.drop_index(op.f('ix_property_settings_last_modified_hlc'), table_name='property_settings')
    op.drop_table('property_settings')
    op.drop_index(op.f('ix_maintenance_tickets_last_modified_hlc'), table_name='maintenance_tickets')
    op.drop_table('maintenance_tickets')
    op.drop_table('lost_and_found')
    op.drop_index(op.f('ix_housekeeping_tasks_last_modified_hlc'), table_name='housekeeping_tasks')
    op.drop_table('housekeeping_tasks')
    op.drop_table('devices')
    op.drop_index(op.f('ix_bookings_last_modified_hlc'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index('ix_audit_logs_property_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module_name'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_last_modified_hlc'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scheduled_reports_template_id'), table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    op.drop_index(op.f('ix_rooms_last_modified_hlc'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_table('role_permissions')
    op.drop_table('subscriptions')
    op.drop_table('room_categories')
    op.drop_table('roles')
    op.drop_index(op.f('ix_report_templates_property_id'), table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_table('pending_dues')
    op.drop_index(op.f('ix_daily_kpi_snapshots_property_id'), table_name='daily_kpi_snapshots')
    op.drop_table('daily_kpi_snapshots')
    op.drop_index(op.f('ix_properties_last_modified_hlc'), table_name='properties')
    op.drop_table('properties')
    op.drop_table('businesses')
    op.drop_table('permissions')
    op.drop_table('owners')
    op.drop_index(op.f('ix_guests_last_modified_hlc'), table_name='guests')
    op.drop_table('guests')
    # ### end Alembic commands ###
