"""Init Schema

Revision ID: 5b407ba6ca21
Revises: 
Create Date: 2026-07-10 12:03:26.380913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b407ba6ca21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guest_id', name=op.f('pk_guests'))
    )
    op.create_table('owners',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('mobile_verified', sa.Boolean(), nullable=False),
    sa.Column('alternate_contact', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('selfie_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('owner_id', name=op.f('pk_owners')),
    sa.UniqueConstraint('email', name=op.f('uq_owners_email')),
    sa.UniqueConstraint('mobile_number', name=op.f('uq_owners_mobile_number'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('permission_code', sa.String(length=60), nullable=False),
    sa.Column('module_name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('permission_code', name=op.f('uq_permissions_permission_code'))
    )
    op.create_table('businesses',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('business_type', sa.String(length=30), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_reg_number', sa.String(length=50), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('gst_certificate_url', sa.Text(), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], name=op.f('fk_businesses_owner_id_owners')),
    sa.PrimaryKeyConstraint('business_id', name=op.f('pk_businesses'))
    )
    op.create_table('properties',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('property_name', sa.String(length=200), nullable=False),
    sa.Column('property_type', sa.String(length=30), nullable=True),
    sa.Column('star_category', sa.SmallInteger(), nullable=True),
    sa.Column('year_established', sa.SmallInteger(), nullable=True),
    sa.Column('total_floors', sa.SmallInteger(), nullable=True),
    sa.Column('total_rooms', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_device_id', sa.UUID(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=15), nullable=True),
    sa.Column('onboarding_status', sa.String(length=20), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], name=op.f('fk_properties_business_id_businesses')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], name=op.f('fk_properties_owner_id_owners')),
    sa.PrimaryKeyConstraint('property_id', name=op.f('pk_properties'))
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('role_code', sa.String(length=40), nullable=False),
    sa.Column('role_name', sa.String(length=80), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_roles_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('property_id', 'role_code', name='uq_roles_property_role_code')
    )
    op.create_table('room_categories',
    sa.Column('room_category_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=True),
    sa.Column('number_of_rooms', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_room_categories_property_id_properties')),
    sa.PrimaryKeyConstraint('room_category_id', name=op.f('pk_room_categories'))
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('room_category_id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('housekeeping_status', sa.String(length=20), nullable=True),
    sa.Column('occupancy_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_category_id'], ['room_categories.room_category_id'], name=op.f('fk_rooms_room_category_id_room_categories')),
    sa.PrimaryKeyConstraint('room_id', name=op.f('pk_rooms'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('biometric_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_primary_owner', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failed_login_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_pending_sync', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_users_property_id_properties')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('target_entity', sa.String(length=50), nullable=True),
    sa.Column('target_record_id', sa.UUID(), nullable=True),
    sa.Column('old_value_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_log_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_audit_logs_property_id_properties')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_module_name'), 'audit_logs', ['module_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('booking_status', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_bookings_guest_id_guests')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_bookings_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_bookings_room_id_rooms')),
    sa.PrimaryKeyConstraint('booking_id', name=op.f('pk_bookings'))
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_uid', sa.String(length=128), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('primary_user_id', sa.UUID(), nullable=True),
    sa.Column('device_name', sa.String(length=80), nullable=True),
    sa.Column('os_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_user_id'], ['users.id'], name=op.f('fk_devices_primary_user_id_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_devices_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('device_uid', name=op.f('uq_devices_device_uid'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module_name'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('rooms')
    op.drop_table('role_permissions')
    op.drop_table('room_categories')
    op.drop_table('roles')
    op.drop_table('properties')
    op.drop_table('businesses')
    op.drop_table('permissions')
    op.drop_table('owners')
    op.drop_table('guests')
    # ### end Alembic commands ###
