"""Make device_id nullable in user_sessions

Revision ID: 6c73c256b2d2
Revises: 5b62b145a1c1
Create Date: 2026-07-17 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c73c256b2d2'
down_revision: Union[str, None] = '5b62b145a1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'device_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'device_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='public')
    # ### end Alembic commands ###
