"""Init Schema

Revision ID: 96baf4e605bd
Revises: 
Create Date: 2026-07-18 22:15:00.237686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96baf4e605bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'owners' in inspector.get_table_names():
        print("Schema already initialized, skipping init_schema migration.")
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('mobile_verified', sa.Boolean(), nullable=False),
    sa.Column('alternate_contact', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('selfie_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('owner_id', name=op.f('pk_owners')),
    sa.UniqueConstraint('email', name=op.f('uq_owners_email')),
    sa.UniqueConstraint('mobile_number', name=op.f('uq_owners_mobile_number')),
    schema='public'
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('permission_code', sa.String(length=60), nullable=False),
    sa.Column('module_name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('permission_code', name=op.f('uq_permissions_permission_code')),
    schema='public'
    )
    op.create_table('user_sync_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sync_log')),
    schema='public'
    )
    op.create_table('businesses',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('business_type', sa.String(length=30), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_reg_number', sa.String(length=50), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('gst_certificate_url', sa.Text(), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['public.owners.owner_id'], name=op.f('fk_businesses_owner_id_owners')),
    sa.PrimaryKeyConstraint('business_id', name=op.f('pk_businesses')),
    schema='public'
    )
    op.create_table('properties',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('property_name', sa.String(length=200), nullable=False),
    sa.Column('property_type', sa.String(length=30), nullable=True),
    sa.Column('star_category', sa.SmallInteger(), nullable=True),
    sa.Column('year_established', sa.SmallInteger(), nullable=True),
    sa.Column('total_floors', sa.SmallInteger(), nullable=True),
    sa.Column('total_rooms', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_device_id', sa.UUID(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=15), nullable=True),
    sa.Column('onboarding_status', sa.String(length=20), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['public.businesses.business_id'], name=op.f('fk_properties_business_id_businesses')),
    sa.ForeignKeyConstraint(['owner_id'], ['public.owners.owner_id'], name=op.f('fk_properties_owner_id_owners')),
    sa.PrimaryKeyConstraint('property_id', name=op.f('pk_properties')),
    schema='public'
    )
    op.create_index(op.f('ix_public_properties_last_modified_hlc'), 'properties', ['last_modified_hlc'], unique=False, schema='public')
    op.create_table('daily_kpi_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('occupied_rooms', sa.Integer(), nullable=False),
    sa.Column('vacant_rooms', sa.Integer(), nullable=False),
    sa.Column('revenue_room_rent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('revenue_addons', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expenses_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding_payments', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_collected', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_daily_kpi_snapshots_property_id_properties')),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_daily_kpi_snapshots')),
    sa.UniqueConstraint('property_id', 'snapshot_date', name='uq_daily_kpi_property_date')
    )
    op.create_index(op.f('ix_daily_kpi_snapshots_property_id'), 'daily_kpi_snapshots', ['property_id'], unique=False)
    op.create_table('guests',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_guests_property_id_properties')),
    sa.PrimaryKeyConstraint('guest_id', name=op.f('pk_guests'))
    )
    op.create_index(op.f('ix_guests_last_modified_hlc'), 'guests', ['last_modified_hlc'], unique=False)
    op.create_table('pending_dues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('reminder_status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_pending_dues_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_dues')),
    schema='public'
    )
    op.create_table('subscription_plans',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_subscription_plans_property_id_properties')),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_subscription_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_subscription_plans_name')),
    schema='public'
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('license_id', sa.String(length=100), nullable=True),
    sa.Column('device_limit', sa.Integer(), nullable=False),
    sa.Column('registered_devices', sa.Integer(), nullable=False),
    sa.Column('subscription_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_subscriptions_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('license_id', name=op.f('uq_subscriptions_license_id')),
    schema='public'
    )
    op.create_table('report_templates',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('report_name', sa.String(length=150), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('configuration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_report_templates_property_id_properties')),
    sa.PrimaryKeyConstraint('template_id', name=op.f('pk_report_templates'))
    )
    op.create_index(op.f('ix_report_templates_property_id'), 'report_templates', ['property_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('role_code', sa.String(length=40), nullable=False),
    sa.Column('role_name', sa.String(length=80), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_roles_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('property_id', 'role_code', name='uq_roles_property_role_code')
    )
    op.create_table('room_categories',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('room_category_id', sa.UUID(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=True),
    sa.Column('number_of_rooms', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_room_categories_property_id_properties')),
    sa.PrimaryKeyConstraint('room_category_id', name=op.f('pk_room_categories'))
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['public.permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions')
    )
    op.create_table('rooms',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('room_category_id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('housekeeping_status', sa.String(length=20), nullable=True),
    sa.Column('occupancy_status', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_rooms_property_id_properties')),
    sa.ForeignKeyConstraint(['room_category_id'], ['room_categories.room_category_id'], name=op.f('fk_rooms_room_category_id_room_categories')),
    sa.PrimaryKeyConstraint('room_id', name=op.f('pk_rooms'))
    )
    op.create_index(op.f('ix_rooms_last_modified_hlc'), 'rooms', ['last_modified_hlc'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('recipient_role', sa.String(length=40), nullable=False),
    sa.Column('delivery_channel', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.template_id'], name=op.f('fk_scheduled_reports_template_id_report_templates')),
    sa.PrimaryKeyConstraint('schedule_id', name=op.f('pk_scheduled_reports'))
    )
    op.create_index(op.f('ix_scheduled_reports_template_id'), 'scheduled_reports', ['template_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('biometric_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_primary_owner', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failed_login_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_pending_sync', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_users_property_id_properties')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('mobile_number', name='uq_users_mobile_number'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index(op.f('ix_users_last_modified_hlc'), 'users', ['last_modified_hlc'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('target_entity', sa.String(length=50), nullable=True),
    sa.Column('target_record_id', sa.UUID(), nullable=True),
    sa.Column('old_value_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('previous_log_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_audit_logs_property_id_properties')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_module_name'), 'audit_logs', ['module_name'], unique=False)
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_entity', 'target_record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('bookings',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('booking_type', sa.String(length=20), nullable=True),
    sa.Column('booking_source', sa.String(length=30), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('room_rent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_payable', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('advance_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pending_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('booking_status', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_bookings_guest_id_guests')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_bookings_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_bookings_room_id_rooms')),
    sa.PrimaryKeyConstraint('booking_id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_last_modified_hlc'), 'bookings', ['last_modified_hlc'], unique=False)
    op.create_table('broker_commission_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('broker_user_id', sa.UUID(), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_user_id'], ['users.id'], name=op.f('fk_broker_commission_rules_broker_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_broker_commission_rules_created_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_broker_commission_rules_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_commission_rules'))
    )
    op.create_table('broker_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_user_id'], ['users.id'], name=op.f('fk_broker_wallets_broker_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_broker_wallets_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_wallets')),
    sa.UniqueConstraint('broker_user_id', 'property_id', name='uq_broker_wallet')
    )
    op.create_table('commission_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_user_id'], ['users.id'], name=op.f('fk_commission_payouts_broker_user_id_users')),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], name=op.f('fk_commission_payouts_initiated_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_commission_payouts_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_payouts'))
    )
    op.create_table('device_blacklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_uid', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('blacklisted_by', sa.UUID(), nullable=True),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blacklisted_by'], ['users.id'], name=op.f('fk_device_blacklist_blacklisted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_blacklist'))
    )
    op.create_index(op.f('ix_device_blacklist_device_uid'), 'device_blacklist', ['device_uid'], unique=True)
    op.create_table('housekeeping_tasks',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('checklist_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], name=op.f('fk_housekeeping_tasks_assigned_staff_id_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_housekeeping_tasks_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_housekeeping_tasks_room_id_rooms')),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_housekeeping_tasks'))
    )
    op.create_index(op.f('ix_housekeeping_tasks_last_modified_hlc'), 'housekeeping_tasks', ['last_modified_hlc'], unique=False)
    op.create_table('lost_and_found',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('found_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['found_by'], ['users.id'], name=op.f('fk_lost_and_found_found_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_lost_and_found_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_lost_and_found_room_id_rooms')),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_lost_and_found'))
    )
    op.create_table('maintenance_tickets',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_maintenance_tickets_assigned_to_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_maintenance_tickets_property_id_properties')),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_maintenance_tickets_reported_by_users')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_maintenance_tickets_room_id_rooms')),
    sa.PrimaryKeyConstraint('ticket_id', name=op.f('pk_maintenance_tickets'))
    )
    op.create_index(op.f('ix_maintenance_tickets_last_modified_hlc'), 'maintenance_tickets', ['last_modified_hlc'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_last_modified_hlc'), 'notifications', ['last_modified_hlc'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('condition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('multiplier', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('flat_adjustment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('days_of_week', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_pricing_rules_created_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_pricing_rules_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_rules'))
    )
    op.create_index('ix_pricing_rules_property_active', 'pricing_rules', ['property_id', 'is_active'], unique=False)
    op.create_table('property_incident_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('witness_name', sa.String(length=150), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_property_incident_reports_property_id_properties')),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_property_incident_reports_reported_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_incident_reports'))
    )
    op.create_table('property_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_property_settings_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_property_settings_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_settings'))
    )
    op.create_index(op.f('ix_property_settings_last_modified_hlc'), 'property_settings', ['last_modified_hlc'], unique=False)
    op.create_index(op.f('ix_property_settings_property_id'), 'property_settings', ['property_id'], unique=False)
    op.create_index('uq_property_settings_active_key', 'property_settings', ['property_id', 'setting_key'], unique=True, postgresql_where=sa.text('is_deleted = FALSE'), sqlite_where=sa.text('is_deleted = FALSE'))
    op.create_table('credential_reset_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reset_type', sa.String(length=20), nullable=False),
    sa.Column('requested_via', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_credential_reset_requests_approved_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credential_reset_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential_reset_requests')),
    schema='public'
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_uid', sa.String(length=128), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('primary_user_id', sa.UUID(), nullable=True),
    sa.Column('device_name', sa.String(length=80), nullable=True),
    sa.Column('os_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_user_id'], ['users.id'], name=op.f('fk_devices_primary_user_id_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_devices_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('device_uid', name=op.f('uq_devices_device_uid')),
    schema='public'
    )
    op.create_table('staff_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('invitation_token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_staff_invitations_invited_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_staff_invitations_property_id_properties')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_staff_invitations_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_invitations')),
    sa.UniqueConstraint('invitation_token', name=op.f('uq_staff_invitations_invitation_token')),
    schema='public'
    )
    op.create_table('security_incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_uid', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_security_incidents_property_id_properties')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_security_incidents_resolved_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_security_incidents_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_incidents'))
    )
    op.create_index('ix_security_incidents_property', 'security_incidents', ['property_id'], unique=False)
    op.create_table('system_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_system_configurations_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_configurations'))
    )
    op.create_index(op.f('ix_system_configurations_config_key'), 'system_configurations', ['config_key'], unique=True)
    op.create_table('user_property_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_user_property_access_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_property_access_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_property_access_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_property_access')),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_user_property_access')
    )
    op.create_table('vehicle_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=30), nullable=True),
    sa.Column('driver_name', sa.String(length=150), nullable=True),
    sa.Column('entry_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], name=op.f('fk_vehicle_logs_logged_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_vehicle_logs_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_logs'))
    )
    op.create_table('visitor_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('visitor_name', sa.String(length=150), nullable=False),
    sa.Column('visitor_mobile', sa.String(length=15), nullable=True),
    sa.Column('host_user_id', sa.UUID(), nullable=True),
    sa.Column('host_room', sa.String(length=20), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('id_type', sa.String(length=30), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('entry_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('logged_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], name=op.f('fk_visitor_logs_host_user_id_users')),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], name=op.f('fk_visitor_logs_logged_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_visitor_logs_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitor_logs'))
    )
    op.create_table('check_ins',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('checkin_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('advance_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id_verified', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_check_ins_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_check_ins_guest_id_guests')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_check_ins_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_check_ins_room_id_rooms')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_check_ins_staff_id_users')),
    sa.PrimaryKeyConstraint('checkin_id', name=op.f('pk_check_ins'))
    )
    op.create_index(op.f('ix_check_ins_last_modified_hlc'), 'check_ins', ['last_modified_hlc'], unique=False)
    op.create_table('folio_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_folio_line_items_added_by_users')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_folio_line_items_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_folio_line_items_property_id_properties')),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], name=op.f('fk_folio_line_items_voided_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folio_line_items'))
    )
    op.create_index('ix_folio_line_items_booking', 'folio_line_items', ['booking_id'], unique=False)
    op.create_table('guest_nationality_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('nationality', sa.String(length=60), nullable=False),
    sa.Column('passport_number', sa.String(length=30), nullable=False),
    sa.Column('passport_expiry', sa.Date(), nullable=True),
    sa.Column('visa_number', sa.String(length=30), nullable=True),
    sa.Column('visa_type', sa.String(length=30), nullable=True),
    sa.Column('visa_expiry', sa.Date(), nullable=True),
    sa.Column('port_of_arrival', sa.String(length=100), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('document_front_url', sa.Text(), nullable=True),
    sa.Column('document_back_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_guest_nationality_documents_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_guest_nationality_documents_guest_id_guests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_guest_nationality_documents_property_id_properties')),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_guest_nationality_documents_verified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_nationality_documents'))
    )
    op.create_table('invoices',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_invoices_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_invoices_guest_id_guests')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_invoices_property_id_properties')),
    sa.PrimaryKeyConstraint('invoice_id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_invoices_invoice_number'))
    )
    op.create_table('otp_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_otp_requests_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otp_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_requests'))
    )
    op.create_index('ix_otp_requests_user_purpose', 'otp_requests', ['user_id', 'purpose'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('is_offline_session', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['public.devices.id'], name=op.f('fk_user_sessions_device_id_devices')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('session_token', name=op.f('uq_user_sessions_session_token')),
    schema='public'
    )
    op.create_table('room_assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_room_assignments_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_room_assignments_guest_id_guests')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_room_assignments_room_id_rooms')),
    sa.PrimaryKeyConstraint('assignment_id', name=op.f('pk_room_assignments'))
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_tasks_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_tasks_booking_id_bookings')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_tasks_room_id_rooms')),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_last_modified_hlc'), 'tasks', ['last_modified_hlc'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('is_primary_device', sa.Boolean(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['public.devices.id'], name=op.f('fk_user_devices_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_devices')),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_devices_user_device')
    )
    op.create_table('check_outs',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('checkout_id', sa.UUID(), nullable=False),
    sa.Column('checkin_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('checkout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('advance_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remaining_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('checkout_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_check_outs_booking_id_bookings')),
    sa.ForeignKeyConstraint(['checkin_id'], ['check_ins.checkin_id'], name=op.f('fk_check_outs_checkin_id_check_ins')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_check_outs_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_check_outs_room_id_rooms')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_check_outs_staff_id_users')),
    sa.PrimaryKeyConstraint('checkout_id', name=op.f('pk_check_outs'))
    )
    op.create_index(op.f('ix_check_outs_last_modified_hlc'), 'check_outs', ['last_modified_hlc'], unique=False)
    op.create_table('form_c_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('nationality_doc_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_form_c_records_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_form_c_records_guest_id_guests')),
    sa.ForeignKeyConstraint(['nationality_doc_id'], ['guest_nationality_documents.id'], name=op.f('fk_form_c_records_nationality_doc_id_guest_nationality_documents')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_form_c_records_property_id_properties')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_form_c_records_submitted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_c_records'))
    )
    op.create_table('invoice_items',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], name=op.f('fk_invoice_items_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_invoice_items'))
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('payment_mode', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_payments_booking_id_bookings')),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], name=op.f('fk_payments_collected_by_users')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], name=op.f('fk_payments_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_payments')),
    sa.UniqueConstraint('transaction_id', name=op.f('uq_payments_transaction_id'))
    )
    op.create_index(op.f('ix_payments_last_modified_hlc'), 'payments', ['last_modified_hlc'], unique=False)
    op.create_table('subscription_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bank_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], name=op.f('fk_subscription_transactions_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_subscription_transactions_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_transactions')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_subscription_transactions_payment_id')),
    schema='public'
    )
    op.create_table('task_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_hlc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_task_logs_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_task_logs'))
    )
    op.create_index(op.f('ix_task_logs_last_modified_hlc'), 'task_logs', ['last_modified_hlc'], unique=False)
    op.create_table('commission_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_wallet_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_applied', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_commission_transactions_booking_id_bookings')),
    sa.ForeignKeyConstraint(['broker_wallet_id'], ['broker_wallets.id'], name=op.f('fk_commission_transactions_broker_wallet_id_broker_wallets')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], name=op.f('fk_commission_transactions_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_transactions'))
    )
    op.create_table('form_c_amendments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_c_id', sa.UUID(), nullable=False),
    sa.Column('amended_by', sa.UUID(), nullable=False),
    sa.Column('amendment_reason', sa.Text(), nullable=False),
    sa.Column('old_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amended_by'], ['users.id'], name=op.f('fk_form_c_amendments_amended_by_users')),
    sa.ForeignKeyConstraint(['form_c_id'], ['form_c_records.id'], name=op.f('fk_form_c_amendments_form_c_id_form_c_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_c_amendments'))
    )
    op.create_table('payment_transactions',
    sa.Column('txn_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], name=op.f('fk_payment_transactions_payment_id_payments')),
    sa.PrimaryKeyConstraint('txn_id', name=op.f('pk_payment_transactions'))
    )
    op.create_table('split_payments',
    sa.Column('split_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], name=op.f('fk_split_payments_payment_id_payments')),
    sa.PrimaryKeyConstraint('split_id', name=op.f('pk_split_payments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('split_payments')
    op.drop_table('payment_transactions')
    op.drop_table('form_c_amendments')
    op.drop_table('commission_transactions')
    op.drop_index(op.f('ix_task_logs_last_modified_hlc'), table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_table('subscription_transactions', schema='public')
    op.drop_index(op.f('ix_payments_last_modified_hlc'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('invoice_items')
    op.drop_table('form_c_records')
    op.drop_index(op.f('ix_check_outs_last_modified_hlc'), table_name='check_outs')
    op.drop_table('check_outs')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_tasks_last_modified_hlc'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('room_assignments')
    op.drop_table('user_sessions', schema='public')
    op.drop_index('ix_otp_requests_user_purpose', table_name='otp_requests')
    op.drop_table('otp_requests')
    op.drop_table('invoices')
    op.drop_table('guest_nationality_documents')
    op.drop_index('ix_folio_line_items_booking', table_name='folio_line_items')
    op.drop_table('folio_line_items')
    op.drop_index(op.f('ix_check_ins_last_modified_hlc'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_table('visitor_logs')
    op.drop_table('vehicle_logs')
    op.drop_table('user_property_access')
    op.drop_index(op.f('ix_system_configurations_config_key'), table_name='system_configurations')
    op.drop_table('system_configurations')
    op.drop_index('ix_security_incidents_property', table_name='security_incidents')
    op.drop_table('security_incidents')
    op.drop_table('staff_invitations', schema='public')
    op.drop_table('devices', schema='public')
    op.drop_table('credential_reset_requests', schema='public')
    op.drop_index('uq_property_settings_active_key', table_name='property_settings', postgresql_where=sa.text('is_deleted = FALSE'), sqlite_where=sa.text('is_deleted = FALSE'))
    op.drop_index(op.f('ix_property_settings_property_id'), table_name='property_settings')
    op.drop_index(op.f('ix_property_settings_last_modified_hlc'), table_name='property_settings')
    op.drop_table('property_settings')
    op.drop_table('property_incident_reports')
    op.drop_index('ix_pricing_rules_property_active', table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_notifications_last_modified_hlc'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_maintenance_tickets_last_modified_hlc'), table_name='maintenance_tickets')
    op.drop_table('maintenance_tickets')
    op.drop_table('lost_and_found')
    op.drop_index(op.f('ix_housekeeping_tasks_last_modified_hlc'), table_name='housekeeping_tasks')
    op.drop_table('housekeeping_tasks')
    op.drop_index(op.f('ix_device_blacklist_device_uid'), table_name='device_blacklist')
    op.drop_table('device_blacklist')
    op.drop_table('commission_payouts')
    op.drop_table('broker_wallets')
    op.drop_table('broker_commission_rules')
    op.drop_index(op.f('ix_bookings_last_modified_hlc'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module_name'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_last_modified_hlc'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scheduled_reports_template_id'), table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    op.drop_index(op.f('ix_rooms_last_modified_hlc'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_table('role_permissions')
    op.drop_table('room_categories')
    op.drop_table('roles')
    op.drop_index(op.f('ix_report_templates_property_id'), table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_table('subscriptions', schema='public')
    op.drop_table('subscription_plans', schema='public')
    op.drop_table('pending_dues', schema='public')
    op.drop_index(op.f('ix_guests_last_modified_hlc'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_daily_kpi_snapshots_property_id'), table_name='daily_kpi_snapshots')
    op.drop_table('daily_kpi_snapshots')
    op.drop_index(op.f('ix_public_properties_last_modified_hlc'), table_name='properties', schema='public')
    op.drop_table('properties', schema='public')
    op.drop_table('businesses', schema='public')
    op.drop_table('user_sync_log', schema='public')
    op.drop_table('permissions', schema='public')
    op.drop_table('owners', schema='public')
    # ### end Alembic commands ###
