"""Add missing tables

Revision ID: c55e83a79a0a
Revises: 5b407ba6ca21
Create Date: 2026-07-10 22:23:09.455203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c55e83a79a0a'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_kpi_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('occupied_rooms', sa.Integer(), nullable=False),
    sa.Column('vacant_rooms', sa.Integer(), nullable=False),
    sa.Column('revenue_room_rent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('revenue_addons', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expenses_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding_payments', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_collected', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_daily_kpi_snapshots_property_id_properties')),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_daily_kpi_snapshots')),
    sa.UniqueConstraint('property_id', 'snapshot_date', name='uq_daily_kpi_property_date')
    )
    op.create_index(op.f('ix_daily_kpi_snapshots_property_id'), 'daily_kpi_snapshots', ['property_id'], unique=False)
    op.create_table('pending_dues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('reminder_status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_pending_dues_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_dues'))
    )
    op.create_table('report_templates',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('report_name', sa.String(length=150), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('configuration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_report_templates_property_id_properties')),
    sa.PrimaryKeyConstraint('template_id', name=op.f('pk_report_templates'))
    )
    op.create_index(op.f('ix_report_templates_property_id'), 'report_templates', ['property_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('license_id', sa.String(length=100), nullable=True),
    sa.Column('device_limit', sa.Integer(), nullable=False),
    sa.Column('registered_devices', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_subscriptions_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('license_id', name=op.f('uq_subscriptions_license_id'))
    )
    op.create_table('scheduled_reports',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('recipient_role', sa.String(length=40), nullable=False),
    sa.Column('delivery_channel', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.template_id'], name=op.f('fk_scheduled_reports_template_id_report_templates')),
    sa.PrimaryKeyConstraint('schedule_id', name=op.f('pk_scheduled_reports'))
    )
    op.create_index(op.f('ix_scheduled_reports_template_id'), 'scheduled_reports', ['template_id'], unique=False)
    op.create_table('housekeeping_tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('checklist_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], name=op.f('fk_housekeeping_tasks_assigned_staff_id_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_housekeeping_tasks_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_housekeeping_tasks_room_id_rooms')),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_housekeeping_tasks'))
    )
    op.create_table('lost_and_found',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('found_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['found_by'], ['users.id'], name=op.f('fk_lost_and_found_found_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_lost_and_found_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_lost_and_found_room_id_rooms')),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_lost_and_found'))
    )
    op.create_table('maintenance_tickets',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_maintenance_tickets_assigned_to_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_maintenance_tickets_property_id_properties')),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_maintenance_tickets_reported_by_users')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_maintenance_tickets_room_id_rooms')),
    sa.PrimaryKeyConstraint('ticket_id', name=op.f('pk_maintenance_tickets'))
    )
    op.create_table('check_ins',
    sa.Column('checkin_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('advance_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id_verified', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_check_ins_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_check_ins_guest_id_guests')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_check_ins_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_check_ins_room_id_rooms')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_check_ins_staff_id_users')),
    sa.PrimaryKeyConstraint('checkin_id', name=op.f('pk_check_ins'))
    )
    op.create_table('invoices',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_invoices_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_invoices_guest_id_guests')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_invoices_property_id_properties')),
    sa.PrimaryKeyConstraint('invoice_id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_invoices_invoice_number'))
    )
    op.create_table('room_assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_room_assignments_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_room_assignments_guest_id_guests')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_room_assignments_room_id_rooms')),
    sa.PrimaryKeyConstraint('assignment_id', name=op.f('pk_room_assignments'))
    )
    op.create_table('check_outs',
    sa.Column('checkout_id', sa.UUID(), nullable=False),
    sa.Column('checkin_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('checkout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('advance_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remaining_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('checkout_status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_check_outs_booking_id_bookings')),
    sa.ForeignKeyConstraint(['checkin_id'], ['check_ins.checkin_id'], name=op.f('fk_check_outs_checkin_id_check_ins')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_check_outs_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_check_outs_room_id_rooms')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_check_outs_staff_id_users')),
    sa.PrimaryKeyConstraint('checkout_id', name=op.f('pk_check_outs'))
    )
    op.create_table('invoice_items',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], name=op.f('fk_invoice_items_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_invoice_items'))
    )
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bank_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], name=op.f('fk_payment_transactions_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_payment_transactions_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_transactions')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_payment_transactions_payment_id'))
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.String(length=60), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_payments_booking_id_bookings')),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], name=op.f('fk_payments_collected_by_users')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_payments_guest_id_guests')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], name=op.f('fk_payments_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_payments_property_id_properties')),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_payments'))
    )
    op.create_table('split_payments',
    sa.Column('split_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], name=op.f('fk_split_payments_payment_id_payments')),
    sa.PrimaryKeyConstraint('split_id', name=op.f('pk_split_payments'))
    )
    op.add_column('bookings', sa.Column('booking_type', sa.String(length=20), nullable=True))
    op.add_column('bookings', sa.Column('booking_source', sa.String(length=30), nullable=True))
    op.add_column('bookings', sa.Column('adults', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('children', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('room_rent', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('deposit', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('taxes', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('total_payable', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('advance_paid', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('pending_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('bookings', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'notes')
    op.drop_column('bookings', 'pending_amount')
    op.drop_column('bookings', 'advance_paid')
    op.drop_column('bookings', 'total_payable')
    op.drop_column('bookings', 'taxes')
    op.drop_column('bookings', 'discount')
    op.drop_column('bookings', 'deposit')
    op.drop_column('bookings', 'room_rent')
    op.drop_column('bookings', 'children')
    op.drop_column('bookings', 'adults')
    op.drop_column('bookings', 'booking_source')
    op.drop_column('bookings', 'booking_type')
    op.drop_table('split_payments')
    op.drop_table('payments')
    op.drop_table('payment_transactions')
    op.drop_table('invoice_items')
    op.drop_table('check_outs')
    op.drop_table('room_assignments')
    op.drop_table('invoices')
    op.drop_table('check_ins')
    op.drop_table('maintenance_tickets')
    op.drop_table('lost_and_found')
    op.drop_table('housekeeping_tasks')
    op.drop_index(op.f('ix_scheduled_reports_template_id'), table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_report_templates_property_id'), table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_table('pending_dues')
    op.drop_index(op.f('ix_daily_kpi_snapshots_property_id'), table_name='daily_kpi_snapshots')
    op.drop_table('daily_kpi_snapshots')
    # ### end Alembic commands ###
