"""Add SecurityCamera and Watchlist models

Revision ID: c9b7e813a94c
Revises: 96baf4e605bd
Create Date: 2026-07-18 22:23:53.109005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b7e813a94c'
down_revision: Union[str, Sequence[str], None] = '96baf4e605bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_security_cameras_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_cameras'))
    )
    op.create_table('watchlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('person_name', sa.String(length=100), nullable=True),
    sa.Column('id_number', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_watchlist_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_watchlist_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist'))
    )
    op.drop_constraint(op.f('fk_audit_logs_property_id_properties'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_logs_property_id_properties'), 'audit_logs', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_bookings_property_id_properties'), 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookings_property_id_properties'), 'bookings', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_broker_commission_rules_property_id_properties'), 'broker_commission_rules', type_='foreignkey')
    op.create_foreign_key(op.f('fk_broker_commission_rules_property_id_properties'), 'broker_commission_rules', 'properties', ['property_id'], ['property_id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_broker_wallets_property_id_properties'), 'broker_wallets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_broker_wallets_property_id_properties'), 'broker_wallets', 'properties', ['property_id'], ['property_id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_businesses_owner_id_owners'), 'businesses', type_='foreignkey')
    op.create_foreign_key(op.f('fk_businesses_owner_id_owners'), 'businesses', 'owners', ['owner_id'], ['owner_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_check_ins_property_id_properties'), 'check_ins', type_='foreignkey')
    op.create_foreign_key(op.f('fk_check_ins_property_id_properties'), 'check_ins', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_check_outs_property_id_properties'), 'check_outs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_check_outs_property_id_properties'), 'check_outs', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_commission_payouts_property_id_properties'), 'commission_payouts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_commission_payouts_property_id_properties'), 'commission_payouts', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_credential_reset_requests_user_id_users'), 'credential_reset_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_credential_reset_requests_approved_by_users'), 'credential_reset_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_credential_reset_requests_user_id_users'), 'credential_reset_requests', 'users', ['user_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_credential_reset_requests_approved_by_users'), 'credential_reset_requests', 'users', ['approved_by'], ['id'], source_schema='public')
    op.drop_constraint(op.f('fk_daily_kpi_snapshots_property_id_properties'), 'daily_kpi_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('fk_daily_kpi_snapshots_property_id_properties'), 'daily_kpi_snapshots', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_devices_property_id_properties'), 'devices', type_='foreignkey')
    op.drop_constraint(op.f('fk_devices_primary_user_id_users'), 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_devices_property_id_properties'), 'devices', 'properties', ['property_id'], ['property_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_devices_primary_user_id_users'), 'devices', 'users', ['primary_user_id'], ['id'], source_schema='public')
    op.drop_constraint(op.f('fk_folio_line_items_property_id_properties'), 'folio_line_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_folio_line_items_property_id_properties'), 'folio_line_items', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_form_c_records_property_id_properties'), 'form_c_records', type_='foreignkey')
    op.create_foreign_key(op.f('fk_form_c_records_property_id_properties'), 'form_c_records', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_guest_nationality_documents_property_id_properties'), 'guest_nationality_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_guest_nationality_documents_property_id_properties'), 'guest_nationality_documents', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_guests_property_id_properties'), 'guests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_guests_property_id_properties'), 'guests', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_housekeeping_tasks_property_id_properties'), 'housekeeping_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_housekeeping_tasks_property_id_properties'), 'housekeeping_tasks', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_invoices_property_id_properties'), 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoices_property_id_properties'), 'invoices', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_lost_and_found_property_id_properties'), 'lost_and_found', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lost_and_found_property_id_properties'), 'lost_and_found', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_maintenance_tickets_property_id_properties'), 'maintenance_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_maintenance_tickets_property_id_properties'), 'maintenance_tickets', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_pending_dues_property_id_properties'), 'pending_dues', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pending_dues_property_id_properties'), 'pending_dues', 'properties', ['property_id'], ['property_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_pricing_rules_property_id_properties'), 'pricing_rules', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pricing_rules_property_id_properties'), 'pricing_rules', 'properties', ['property_id'], ['property_id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_properties_business_id_businesses'), 'properties', type_='foreignkey')
    op.drop_constraint(op.f('fk_properties_owner_id_owners'), 'properties', type_='foreignkey')
    op.create_foreign_key(op.f('fk_properties_owner_id_owners'), 'properties', 'owners', ['owner_id'], ['owner_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_properties_business_id_businesses'), 'properties', 'businesses', ['business_id'], ['business_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_property_incident_reports_property_id_properties'), 'property_incident_reports', type_='foreignkey')
    op.create_foreign_key(op.f('fk_property_incident_reports_property_id_properties'), 'property_incident_reports', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_property_settings_property_id_properties'), 'property_settings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_property_settings_property_id_properties'), 'property_settings', 'properties', ['property_id'], ['property_id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_report_templates_property_id_properties'), 'report_templates', type_='foreignkey')
    op.create_foreign_key(op.f('fk_report_templates_property_id_properties'), 'report_templates', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', 'permissions', ['permission_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_roles_property_id_properties'), 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_roles_property_id_properties'), 'roles', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_room_categories_property_id_properties'), 'room_categories', type_='foreignkey')
    op.create_foreign_key(op.f('fk_room_categories_property_id_properties'), 'room_categories', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_rooms_property_id_properties'), 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('fk_rooms_property_id_properties'), 'rooms', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_security_incidents_property_id_properties'), 'security_incidents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_security_incidents_property_id_properties'), 'security_incidents', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_staff_invitations_role_id_roles'), 'staff_invitations', type_='foreignkey')
    op.drop_constraint(op.f('fk_staff_invitations_property_id_properties'), 'staff_invitations', type_='foreignkey')
    op.drop_constraint(op.f('fk_staff_invitations_invited_by_users'), 'staff_invitations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_staff_invitations_invited_by_users'), 'staff_invitations', 'users', ['invited_by'], ['id'], source_schema='public')
    op.create_foreign_key(op.f('fk_staff_invitations_role_id_roles'), 'staff_invitations', 'roles', ['role_id'], ['id'], source_schema='public')
    op.create_foreign_key(op.f('fk_staff_invitations_property_id_properties'), 'staff_invitations', 'properties', ['property_id'], ['property_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_subscription_plans_property_id_properties'), 'subscription_plans', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscription_plans_property_id_properties'), 'subscription_plans', 'properties', ['property_id'], ['property_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_subscription_transactions_invoice_id_invoices'), 'subscription_transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_subscription_transactions_property_id_properties'), 'subscription_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscription_transactions_property_id_properties'), 'subscription_transactions', 'properties', ['property_id'], ['property_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_subscription_transactions_invoice_id_invoices'), 'subscription_transactions', 'invoices', ['invoice_id'], ['invoice_id'], source_schema='public')
    op.drop_constraint(op.f('fk_subscriptions_property_id_properties'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscriptions_property_id_properties'), 'subscriptions', 'properties', ['property_id'], ['property_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_user_devices_device_id_devices'), 'user_devices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_devices_device_id_devices'), 'user_devices', 'devices', ['device_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_user_property_access_property_id_properties'), 'user_property_access', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_property_access_property_id_properties'), 'user_property_access', 'properties', ['property_id'], ['property_id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_user_sessions_device_id_devices'), 'user_sessions', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_sessions_user_id_users'), 'user_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_sessions_device_id_devices'), 'user_sessions', 'devices', ['device_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_user_sessions_user_id_users'), 'user_sessions', 'users', ['user_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_users_property_id_properties'), 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_property_id_properties'), 'users', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_vehicle_logs_property_id_properties'), 'vehicle_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vehicle_logs_property_id_properties'), 'vehicle_logs', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_visitor_logs_property_id_properties'), 'visitor_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_visitor_logs_property_id_properties'), 'visitor_logs', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_visitor_logs_property_id_properties'), 'visitor_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_visitor_logs_property_id_properties'), 'visitor_logs', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_vehicle_logs_property_id_properties'), 'vehicle_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vehicle_logs_property_id_properties'), 'vehicle_logs', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_users_property_id_properties'), 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_property_id_properties'), 'users', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_user_sessions_user_id_users'), 'user_sessions', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_sessions_device_id_devices'), 'user_sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_sessions_user_id_users'), 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_user_sessions_device_id_devices'), 'user_sessions', 'devices', ['device_id'], ['id'])
    op.drop_constraint(op.f('fk_user_property_access_property_id_properties'), 'user_property_access', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_property_access_property_id_properties'), 'user_property_access', 'properties', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_user_devices_device_id_devices'), 'user_devices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_devices_device_id_devices'), 'user_devices', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_subscriptions_property_id_properties'), 'subscriptions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscriptions_property_id_properties'), 'subscriptions', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_subscription_transactions_invoice_id_invoices'), 'subscription_transactions', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_subscription_transactions_property_id_properties'), 'subscription_transactions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscription_transactions_property_id_properties'), 'subscription_transactions', 'properties', ['property_id'], ['property_id'])
    op.create_foreign_key(op.f('fk_subscription_transactions_invoice_id_invoices'), 'subscription_transactions', 'invoices', ['invoice_id'], ['invoice_id'])
    op.drop_constraint(op.f('fk_subscription_plans_property_id_properties'), 'subscription_plans', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscription_plans_property_id_properties'), 'subscription_plans', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_staff_invitations_property_id_properties'), 'staff_invitations', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_staff_invitations_role_id_roles'), 'staff_invitations', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_staff_invitations_invited_by_users'), 'staff_invitations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_staff_invitations_invited_by_users'), 'staff_invitations', 'users', ['invited_by'], ['id'])
    op.create_foreign_key(op.f('fk_staff_invitations_property_id_properties'), 'staff_invitations', 'properties', ['property_id'], ['property_id'])
    op.create_foreign_key(op.f('fk_staff_invitations_role_id_roles'), 'staff_invitations', 'roles', ['role_id'], ['id'])
    op.drop_constraint(op.f('fk_security_incidents_property_id_properties'), 'security_incidents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_security_incidents_property_id_properties'), 'security_incidents', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_rooms_property_id_properties'), 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('fk_rooms_property_id_properties'), 'rooms', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_room_categories_property_id_properties'), 'room_categories', type_='foreignkey')
    op.create_foreign_key(op.f('fk_room_categories_property_id_properties'), 'room_categories', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_roles_property_id_properties'), 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_roles_property_id_properties'), 'roles', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_report_templates_property_id_properties'), 'report_templates', type_='foreignkey')
    op.create_foreign_key(op.f('fk_report_templates_property_id_properties'), 'report_templates', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_property_settings_property_id_properties'), 'property_settings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_property_settings_property_id_properties'), 'property_settings', 'properties', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_property_incident_reports_property_id_properties'), 'property_incident_reports', type_='foreignkey')
    op.create_foreign_key(op.f('fk_property_incident_reports_property_id_properties'), 'property_incident_reports', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_properties_business_id_businesses'), 'properties', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_properties_owner_id_owners'), 'properties', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_properties_owner_id_owners'), 'properties', 'owners', ['owner_id'], ['owner_id'])
    op.create_foreign_key(op.f('fk_properties_business_id_businesses'), 'properties', 'businesses', ['business_id'], ['business_id'])
    op.drop_constraint(op.f('fk_pricing_rules_property_id_properties'), 'pricing_rules', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pricing_rules_property_id_properties'), 'pricing_rules', 'properties', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_pending_dues_property_id_properties'), 'pending_dues', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pending_dues_property_id_properties'), 'pending_dues', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_maintenance_tickets_property_id_properties'), 'maintenance_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_maintenance_tickets_property_id_properties'), 'maintenance_tickets', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_lost_and_found_property_id_properties'), 'lost_and_found', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lost_and_found_property_id_properties'), 'lost_and_found', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_invoices_property_id_properties'), 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoices_property_id_properties'), 'invoices', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_housekeeping_tasks_property_id_properties'), 'housekeeping_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_housekeeping_tasks_property_id_properties'), 'housekeeping_tasks', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_guests_property_id_properties'), 'guests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_guests_property_id_properties'), 'guests', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_guest_nationality_documents_property_id_properties'), 'guest_nationality_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_guest_nationality_documents_property_id_properties'), 'guest_nationality_documents', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_form_c_records_property_id_properties'), 'form_c_records', type_='foreignkey')
    op.create_foreign_key(op.f('fk_form_c_records_property_id_properties'), 'form_c_records', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_folio_line_items_property_id_properties'), 'folio_line_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_folio_line_items_property_id_properties'), 'folio_line_items', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_devices_primary_user_id_users'), 'devices', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_devices_property_id_properties'), 'devices', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_devices_primary_user_id_users'), 'devices', 'users', ['primary_user_id'], ['id'])
    op.create_foreign_key(op.f('fk_devices_property_id_properties'), 'devices', 'properties', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_daily_kpi_snapshots_property_id_properties'), 'daily_kpi_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('fk_daily_kpi_snapshots_property_id_properties'), 'daily_kpi_snapshots', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_credential_reset_requests_approved_by_users'), 'credential_reset_requests', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_credential_reset_requests_user_id_users'), 'credential_reset_requests', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_credential_reset_requests_approved_by_users'), 'credential_reset_requests', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(op.f('fk_credential_reset_requests_user_id_users'), 'credential_reset_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_commission_payouts_property_id_properties'), 'commission_payouts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_commission_payouts_property_id_properties'), 'commission_payouts', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_check_outs_property_id_properties'), 'check_outs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_check_outs_property_id_properties'), 'check_outs', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_check_ins_property_id_properties'), 'check_ins', type_='foreignkey')
    op.create_foreign_key(op.f('fk_check_ins_property_id_properties'), 'check_ins', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_businesses_owner_id_owners'), 'businesses', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_businesses_owner_id_owners'), 'businesses', 'owners', ['owner_id'], ['owner_id'])
    op.drop_constraint(op.f('fk_broker_wallets_property_id_properties'), 'broker_wallets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_broker_wallets_property_id_properties'), 'broker_wallets', 'properties', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_broker_commission_rules_property_id_properties'), 'broker_commission_rules', type_='foreignkey')
    op.create_foreign_key(op.f('fk_broker_commission_rules_property_id_properties'), 'broker_commission_rules', 'properties', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_bookings_property_id_properties'), 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookings_property_id_properties'), 'bookings', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_audit_logs_property_id_properties'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_logs_property_id_properties'), 'audit_logs', 'properties', ['property_id'], ['property_id'])
    op.drop_table('watchlist')
    op.drop_table('security_cameras')
    # ### end Alembic commands ###
