"""Add Wave 3 models

Revision ID: ce8d1f740ae7
Revises: e8e3a2b1c4d5
Create Date: 2026-07-18 22:08:57.954905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce8d1f740ae7'
down_revision: Union[str, Sequence[str], None] = 'e8e3a2b1c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_commission_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('broker_user_id', sa.UUID(), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_user_id'], ['users.id'], name=op.f('fk_broker_commission_rules_broker_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_broker_commission_rules_created_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_broker_commission_rules_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_commission_rules'))
    )
    op.create_table('broker_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_user_id'], ['users.id'], name=op.f('fk_broker_wallets_broker_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_broker_wallets_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_wallets')),
    sa.UniqueConstraint('broker_user_id', 'property_id', name='uq_broker_wallet')
    )
    op.create_table('commission_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_user_id'], ['users.id'], name=op.f('fk_commission_payouts_broker_user_id_users')),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], name=op.f('fk_commission_payouts_initiated_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_commission_payouts_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_payouts'))
    )
    op.create_table('device_blacklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_uid', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('blacklisted_by', sa.UUID(), nullable=True),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blacklisted_by'], ['users.id'], name=op.f('fk_device_blacklist_blacklisted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_blacklist'))
    )
    op.create_index(op.f('ix_device_blacklist_device_uid'), 'device_blacklist', ['device_uid'], unique=True)
    op.create_table('pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('condition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('multiplier', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('flat_adjustment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('days_of_week', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_pricing_rules_created_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_pricing_rules_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_rules'))
    )
    op.create_index('ix_pricing_rules_property_active', 'pricing_rules', ['property_id', 'is_active'], unique=False)
    op.create_table('property_incident_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('witness_name', sa.String(length=150), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_property_incident_reports_property_id_properties')),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_property_incident_reports_reported_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_incident_reports'))
    )
    op.create_table('security_incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_uid', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_security_incidents_property_id_properties')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_security_incidents_resolved_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_security_incidents_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_incidents'))
    )
    op.create_index('ix_security_incidents_property', 'security_incidents', ['property_id'], unique=False)
    op.create_table('vehicle_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=30), nullable=True),
    sa.Column('driver_name', sa.String(length=150), nullable=True),
    sa.Column('entry_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], name=op.f('fk_vehicle_logs_logged_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_vehicle_logs_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_logs'))
    )
    op.create_table('visitor_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('visitor_name', sa.String(length=150), nullable=False),
    sa.Column('visitor_mobile', sa.String(length=15), nullable=True),
    sa.Column('host_user_id', sa.UUID(), nullable=True),
    sa.Column('host_room', sa.String(length=20), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('id_type', sa.String(length=30), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('entry_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('logged_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], name=op.f('fk_visitor_logs_host_user_id_users')),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], name=op.f('fk_visitor_logs_logged_by_users')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_visitor_logs_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitor_logs'))
    )
    op.create_table('folio_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_folio_line_items_added_by_users')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_folio_line_items_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_folio_line_items_property_id_properties')),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], name=op.f('fk_folio_line_items_voided_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folio_line_items'))
    )
    op.create_index('ix_folio_line_items_booking', 'folio_line_items', ['booking_id'], unique=False)
    op.create_table('guest_nationality_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('nationality', sa.String(length=60), nullable=False),
    sa.Column('passport_number', sa.String(length=30), nullable=False),
    sa.Column('passport_expiry', sa.Date(), nullable=True),
    sa.Column('visa_number', sa.String(length=30), nullable=True),
    sa.Column('visa_type', sa.String(length=30), nullable=True),
    sa.Column('visa_expiry', sa.Date(), nullable=True),
    sa.Column('port_of_arrival', sa.String(length=100), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('document_front_url', sa.Text(), nullable=True),
    sa.Column('document_back_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_guest_nationality_documents_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_guest_nationality_documents_guest_id_guests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_guest_nationality_documents_property_id_properties')),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_guest_nationality_documents_verified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_nationality_documents'))
    )
    op.create_table('otp_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_otp_requests_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otp_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_requests'))
    )
    op.create_index('ix_otp_requests_user_purpose', 'otp_requests', ['user_id', 'purpose'], unique=False)
    op.create_table('form_c_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('nationality_doc_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_form_c_records_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], name=op.f('fk_form_c_records_guest_id_guests')),
    sa.ForeignKeyConstraint(['nationality_doc_id'], ['guest_nationality_documents.id'], name=op.f('fk_form_c_records_nationality_doc_id_guest_nationality_documents')),
    sa.ForeignKeyConstraint(['property_id'], ['public.properties.property_id'], name=op.f('fk_form_c_records_property_id_properties')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_form_c_records_submitted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_c_records'))
    )
    op.create_table('commission_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_wallet_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_applied', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_commission_transactions_booking_id_bookings')),
    sa.ForeignKeyConstraint(['broker_wallet_id'], ['broker_wallets.id'], name=op.f('fk_commission_transactions_broker_wallet_id_broker_wallets')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], name=op.f('fk_commission_transactions_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_transactions'))
    )
    op.create_table('form_c_amendments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_c_id', sa.UUID(), nullable=False),
    sa.Column('amended_by', sa.UUID(), nullable=False),
    sa.Column('amendment_reason', sa.Text(), nullable=False),
    sa.Column('old_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amended_by'], ['users.id'], name=op.f('fk_form_c_amendments_amended_by_users')),
    sa.ForeignKeyConstraint(['form_c_id'], ['form_c_records.id'], name=op.f('fk_form_c_amendments_form_c_id_form_c_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_c_amendments'))
    )
    op.drop_index(op.f('ix_audit_logs_property_timestamp'), table_name='audit_logs')
    op.drop_constraint(op.f('fk_audit_logs_property_id_properties'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_logs_property_id_properties'), 'audit_logs', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_bookings_property_id_properties'), 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookings_property_id_properties'), 'bookings', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_businesses_owner_id_owners'), 'businesses', type_='foreignkey')
    op.create_foreign_key(op.f('fk_businesses_owner_id_owners'), 'businesses', 'owners', ['owner_id'], ['owner_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_check_ins_property_id_properties'), 'check_ins', type_='foreignkey')
    op.create_foreign_key(op.f('fk_check_ins_property_id_properties'), 'check_ins', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_check_outs_property_id_properties'), 'check_outs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_check_outs_property_id_properties'), 'check_outs', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_credential_reset_requests_user_id_users'), 'credential_reset_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_credential_reset_requests_approved_by_users'), 'credential_reset_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_credential_reset_requests_user_id_users'), 'credential_reset_requests', 'users', ['user_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_credential_reset_requests_approved_by_users'), 'credential_reset_requests', 'users', ['approved_by'], ['id'], source_schema='public')
    op.drop_constraint(op.f('fk_daily_kpi_snapshots_property_id_properties'), 'daily_kpi_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('fk_daily_kpi_snapshots_property_id_properties'), 'daily_kpi_snapshots', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_devices_primary_user_id_users'), 'devices', type_='foreignkey')
    op.drop_constraint(op.f('fk_devices_property_id_properties'), 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_devices_property_id_properties'), 'devices', 'properties', ['property_id'], ['property_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_devices_primary_user_id_users'), 'devices', 'users', ['primary_user_id'], ['id'], source_schema='public')
    op.alter_column('guests', 'property_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('fk_guests_property_id_properties'), 'guests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_guests_property_id_properties'), 'guests', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_housekeeping_tasks_property_id_properties'), 'housekeeping_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_housekeeping_tasks_property_id_properties'), 'housekeeping_tasks', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_invoices_property_id_properties'), 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoices_property_id_properties'), 'invoices', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_lost_and_found_property_id_properties'), 'lost_and_found', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lost_and_found_property_id_properties'), 'lost_and_found', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_maintenance_tickets_property_id_properties'), 'maintenance_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_maintenance_tickets_property_id_properties'), 'maintenance_tickets', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.add_column('notifications', sa.Column('last_modified_hlc', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('device_id', sa.String(), nullable=True))
    op.alter_column('notifications', 'channel',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('notifications', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_notifications_last_modified_hlc'), 'notifications', ['last_modified_hlc'], unique=False)
    op.drop_constraint(op.f('fk_pending_dues_property_id_properties'), 'pending_dues', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pending_dues_property_id_properties'), 'pending_dues', 'properties', ['property_id'], ['property_id'], source_schema='public', referent_schema='public')
    op.drop_index(op.f('ix_properties_last_modified_hlc'), table_name='properties')
    op.create_index(op.f('ix_public_properties_last_modified_hlc'), 'properties', ['last_modified_hlc'], unique=False, schema='public')
    op.drop_constraint(op.f('fk_properties_business_id_businesses'), 'properties', type_='foreignkey')
    op.drop_constraint(op.f('fk_properties_owner_id_owners'), 'properties', type_='foreignkey')
    op.create_foreign_key(op.f('fk_properties_owner_id_owners'), 'properties', 'owners', ['owner_id'], ['owner_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_properties_business_id_businesses'), 'properties', 'businesses', ['business_id'], ['business_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_property_settings_property_id_properties'), 'property_settings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_property_settings_property_id_properties'), 'property_settings', 'properties', ['property_id'], ['property_id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_report_templates_property_id_properties'), 'report_templates', type_='foreignkey')
    op.create_foreign_key(op.f('fk_report_templates_property_id_properties'), 'report_templates', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.alter_column('role_permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', 'permissions', ['permission_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_roles_property_id_properties'), 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_roles_property_id_properties'), 'roles', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_room_categories_property_id_properties'), 'room_categories', type_='foreignkey')
    op.create_foreign_key(op.f('fk_room_categories_property_id_properties'), 'room_categories', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.alter_column('rooms', 'property_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('rooms', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_rooms_property_id_properties'), 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('fk_rooms_property_id_properties'), 'rooms', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    op.drop_constraint(op.f('fk_staff_invitations_invited_by_users'), 'staff_invitations', type_='foreignkey')
    op.drop_constraint(op.f('fk_staff_invitations_role_id_roles'), 'staff_invitations', type_='foreignkey')
    op.drop_constraint(op.f('fk_staff_invitations_property_id_properties'), 'staff_invitations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_staff_invitations_invited_by_users'), 'staff_invitations', 'users', ['invited_by'], ['id'], source_schema='public')
    op.create_foreign_key(op.f('fk_staff_invitations_role_id_roles'), 'staff_invitations', 'roles', ['role_id'], ['id'], source_schema='public')
    op.create_foreign_key(op.f('fk_staff_invitations_property_id_properties'), 'staff_invitations', 'properties', ['property_id'], ['property_id'], source_schema='public', referent_schema='public')
    op.add_column('subscription_plans', sa.Column('property_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_subscription_plans_property_id_properties'), 'subscription_plans', 'properties', ['property_id'], ['property_id'], source_schema='public', referent_schema='public')
    op.drop_column('subscription_plans', 'description')
    op.drop_column('subscription_plans', 'device_limit')
    op.drop_column('subscription_plans', 'id')
    op.drop_constraint(op.f('fk_subscription_transactions_property_id_properties'), 'subscription_transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_subscription_transactions_invoice_id_invoices'), 'subscription_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscription_transactions_invoice_id_invoices'), 'subscription_transactions', 'invoices', ['invoice_id'], ['invoice_id'], source_schema='public')
    op.create_foreign_key(op.f('fk_subscription_transactions_property_id_properties'), 'subscription_transactions', 'properties', ['property_id'], ['property_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_subscriptions_property_id_properties'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscriptions_property_id_properties'), 'subscriptions', 'properties', ['property_id'], ['property_id'], source_schema='public', referent_schema='public')
    op.add_column('task_logs', sa.Column('last_modified_hlc', sa.String(), nullable=False))
    op.add_column('task_logs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('task_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('task_logs', sa.Column('device_id', sa.String(), nullable=True))
    op.alter_column('task_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_task_logs_last_modified_hlc'), 'task_logs', ['last_modified_hlc'], unique=False)
    op.drop_column('task_logs', 'sync_version')
    op.drop_column('task_logs', 'sync_status')
    op.drop_column('task_logs', 'last_synced_at')
    op.add_column('tasks', sa.Column('last_modified_hlc', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('device_id', sa.String(), nullable=True))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_tasks_last_modified_hlc'), 'tasks', ['last_modified_hlc'], unique=False)
    op.drop_column('tasks', 'sync_version')
    op.drop_column('tasks', 'sync_status')
    op.drop_column('tasks', 'last_synced_at')
    op.drop_constraint(op.f('fk_user_devices_device_id_devices'), 'user_devices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_devices_device_id_devices'), 'user_devices', 'devices', ['device_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.alter_column('user_property_access', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(op.f('fk_user_property_access_property_id_properties'), 'user_property_access', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_property_access_property_id_properties'), 'user_property_access', 'properties', ['property_id'], ['property_id'], referent_schema='public', ondelete='CASCADE')
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_sessions', 'device_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_sessions', 'session_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_sessions', 'is_offline_session',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_sessions', 'issued_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_user_sessions_session_token'), 'user_sessions', ['session_token'], schema='public')
    op.create_foreign_key(op.f('fk_user_sessions_user_id_users'), 'user_sessions', 'users', ['user_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_user_sessions_device_id_devices'), 'user_sessions', 'devices', ['device_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=60),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_users_property_id_properties'), 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_property_id_properties'), 'users', 'properties', ['property_id'], ['property_id'], referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_property_id_properties'), 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_property_id_properties'), 'users', 'properties', ['property_id'], ['property_id'])
    op.alter_column('users', 'username',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_user_sessions_device_id_devices'), 'user_sessions', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_sessions_user_id_users'), 'user_sessions', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('uq_user_sessions_session_token'), 'user_sessions', schema='public', type_='unique')
    op.alter_column('user_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_sessions', 'issued_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'is_offline_session',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_sessions', 'session_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_sessions', 'device_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_user_property_access_property_id_properties'), 'user_property_access', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_property_access_property_id_properties'), 'user_property_access', 'properties', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.alter_column('user_property_access', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(op.f('fk_user_devices_device_id_devices'), 'user_devices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_devices_device_id_devices'), 'user_devices', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('sync_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('sync_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tasks_last_modified_hlc'), table_name='tasks')
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('tasks', 'device_id')
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'is_deleted')
    op.drop_column('tasks', 'last_modified_hlc')
    op.add_column('task_logs', sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('task_logs', sa.Column('sync_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.add_column('task_logs', sa.Column('sync_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_task_logs_last_modified_hlc'), table_name='task_logs')
    op.alter_column('task_logs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('task_logs', 'device_id')
    op.drop_column('task_logs', 'deleted_at')
    op.drop_column('task_logs', 'is_deleted')
    op.drop_column('task_logs', 'last_modified_hlc')
    op.drop_constraint(op.f('fk_subscriptions_property_id_properties'), 'subscriptions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscriptions_property_id_properties'), 'subscriptions', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_subscription_transactions_property_id_properties'), 'subscription_transactions', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_subscription_transactions_invoice_id_invoices'), 'subscription_transactions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscription_transactions_invoice_id_invoices'), 'subscription_transactions', 'invoices', ['invoice_id'], ['invoice_id'])
    op.create_foreign_key(op.f('fk_subscription_transactions_property_id_properties'), 'subscription_transactions', 'properties', ['property_id'], ['property_id'])
    op.add_column('subscription_plans', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('subscription_plans', sa.Column('device_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subscription_plans', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_subscription_plans_property_id_properties'), 'subscription_plans', schema='public', type_='foreignkey')
    op.drop_column('subscription_plans', 'property_id')
    op.drop_constraint(op.f('fk_staff_invitations_property_id_properties'), 'staff_invitations', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_staff_invitations_role_id_roles'), 'staff_invitations', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_staff_invitations_invited_by_users'), 'staff_invitations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_staff_invitations_property_id_properties'), 'staff_invitations', 'properties', ['property_id'], ['property_id'])
    op.create_foreign_key(op.f('fk_staff_invitations_role_id_roles'), 'staff_invitations', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('fk_staff_invitations_invited_by_users'), 'staff_invitations', 'users', ['invited_by'], ['id'])
    op.drop_constraint(op.f('fk_rooms_property_id_properties'), 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('fk_rooms_property_id_properties'), 'rooms', 'properties', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.alter_column('rooms', 'image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('rooms', 'property_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_room_categories_property_id_properties'), 'room_categories', type_='foreignkey')
    op.create_foreign_key(op.f('fk_room_categories_property_id_properties'), 'room_categories', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_roles_property_id_properties'), 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_roles_property_id_properties'), 'roles', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.alter_column('role_permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_report_templates_property_id_properties'), 'report_templates', type_='foreignkey')
    op.create_foreign_key(op.f('fk_report_templates_property_id_properties'), 'report_templates', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_property_settings_property_id_properties'), 'property_settings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_property_settings_property_id_properties'), 'property_settings', 'properties', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_properties_business_id_businesses'), 'properties', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_properties_owner_id_owners'), 'properties', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_properties_owner_id_owners'), 'properties', 'owners', ['owner_id'], ['owner_id'])
    op.create_foreign_key(op.f('fk_properties_business_id_businesses'), 'properties', 'businesses', ['business_id'], ['business_id'])
    op.drop_index(op.f('ix_public_properties_last_modified_hlc'), table_name='properties', schema='public')
    op.create_index(op.f('ix_properties_last_modified_hlc'), 'properties', ['last_modified_hlc'], unique=False)
    op.drop_constraint(op.f('fk_pending_dues_property_id_properties'), 'pending_dues', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pending_dues_property_id_properties'), 'pending_dues', 'properties', ['property_id'], ['property_id'])
    op.drop_index(op.f('ix_notifications_last_modified_hlc'), table_name='notifications')
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('notifications', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('notifications', 'channel',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('notifications', 'device_id')
    op.drop_column('notifications', 'deleted_at')
    op.drop_column('notifications', 'is_deleted')
    op.drop_column('notifications', 'last_modified_hlc')
    op.drop_constraint(op.f('fk_maintenance_tickets_property_id_properties'), 'maintenance_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_maintenance_tickets_property_id_properties'), 'maintenance_tickets', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_lost_and_found_property_id_properties'), 'lost_and_found', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lost_and_found_property_id_properties'), 'lost_and_found', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_invoices_property_id_properties'), 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoices_property_id_properties'), 'invoices', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_housekeeping_tasks_property_id_properties'), 'housekeeping_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_housekeeping_tasks_property_id_properties'), 'housekeeping_tasks', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_guests_property_id_properties'), 'guests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_guests_property_id_properties'), 'guests', 'properties', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.alter_column('guests', 'property_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_devices_primary_user_id_users'), 'devices', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_devices_property_id_properties'), 'devices', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_devices_property_id_properties'), 'devices', 'properties', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_devices_primary_user_id_users'), 'devices', 'users', ['primary_user_id'], ['id'])
    op.drop_constraint(op.f('fk_daily_kpi_snapshots_property_id_properties'), 'daily_kpi_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('fk_daily_kpi_snapshots_property_id_properties'), 'daily_kpi_snapshots', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_credential_reset_requests_approved_by_users'), 'credential_reset_requests', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_credential_reset_requests_user_id_users'), 'credential_reset_requests', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_credential_reset_requests_approved_by_users'), 'credential_reset_requests', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(op.f('fk_credential_reset_requests_user_id_users'), 'credential_reset_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_check_outs_property_id_properties'), 'check_outs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_check_outs_property_id_properties'), 'check_outs', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_check_ins_property_id_properties'), 'check_ins', type_='foreignkey')
    op.create_foreign_key(op.f('fk_check_ins_property_id_properties'), 'check_ins', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_businesses_owner_id_owners'), 'businesses', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_businesses_owner_id_owners'), 'businesses', 'owners', ['owner_id'], ['owner_id'])
    op.drop_constraint(op.f('fk_bookings_property_id_properties'), 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookings_property_id_properties'), 'bookings', 'properties', ['property_id'], ['property_id'])
    op.drop_constraint(op.f('fk_audit_logs_property_id_properties'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_logs_property_id_properties'), 'audit_logs', 'properties', ['property_id'], ['property_id'])
    op.create_index(op.f('ix_audit_logs_property_timestamp'), 'audit_logs', ['property_id', 'timestamp'], unique=False)
    op.create_table('staff_performance',
    sa.Column('performance_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('review_period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('review_period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('attendance_score', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('task_completion_score', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('review_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_staff_performance_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_staff_performance_staff_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('performance_id', name=op.f('pk_staff_performance'))
    )
    op.create_table('licenses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('license_key', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_licenses_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licenses')),
    sa.UniqueConstraint('license_key', name=op.f('uq_licenses_license_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('staff_documents',
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('document_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('verified_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_staff_documents_staff_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_staff_documents_verified_by_users')),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_staff_documents'))
    )
    op.create_table('staff_sessions',
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('login_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('logout_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('login_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_staff_sessions_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_staff_sessions_staff_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_staff_sessions'))
    )
    op.create_table('staff_attendance',
    sa.Column('attendance_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attendance_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('check_out_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('check_in_method', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('check_in_lat', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('check_in_lng', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('marked_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_modified_hlc', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], name=op.f('fk_staff_attendance_marked_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_staff_attendance_property_id_properties')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_staff_attendance_staff_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id', name=op.f('pk_staff_attendance')),
    sa.UniqueConstraint('staff_id', 'attendance_date', name=op.f('uq_staff_attendance_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_staff_attendance_last_modified_hlc'), 'staff_attendance', ['last_modified_hlc'], unique=False)
    op.create_table('staff_salary',
    sa.Column('salary_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('salary_month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salary_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('basic_salary', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('allowances', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('overtime_amount', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('deductions', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('advance_deducted', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('net_salary', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('generated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_staff_salary_generated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_staff_salary_staff_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('salary_id', name=op.f('pk_staff_salary')),
    sa.UniqueConstraint('staff_id', 'salary_month', 'salary_year', name=op.f('uq_staff_salary_month_year'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('staff_leave',
    sa.Column('leave_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('leave_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('to_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('applied_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('approved_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('last_modified_hlc', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_staff_leave_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.leave_type_id'], name=op.f('fk_staff_leave_leave_type_id_leave_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_staff_leave_staff_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('leave_id', name=op.f('pk_staff_leave'))
    )
    op.create_index(op.f('ix_staff_leave_last_modified_hlc'), 'staff_leave', ['last_modified_hlc'], unique=False)
    op.create_table('leave_types',
    sa.Column('leave_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('max_days_per_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_leave_types_property_id_properties')),
    sa.PrimaryKeyConstraint('leave_type_id', name=op.f('pk_leave_types'))
    )
    op.create_table('staff_tasks',
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('task_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('related_module', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('related_record_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completion_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completion_photo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_modified_hlc', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_staff_tasks_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('fk_staff_tasks_property_id_properties')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_staff_tasks_staff_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_staff_tasks'))
    )
    op.create_index(op.f('ix_staff_tasks_last_modified_hlc'), 'staff_tasks', ['last_modified_hlc'], unique=False)
    op.drop_table('form_c_amendments')
    op.drop_table('commission_transactions')
    op.drop_table('form_c_records')
    op.drop_index('ix_otp_requests_user_purpose', table_name='otp_requests')
    op.drop_table('otp_requests')
    op.drop_table('guest_nationality_documents')
    op.drop_index('ix_folio_line_items_booking', table_name='folio_line_items')
    op.drop_table('folio_line_items')
    op.drop_table('visitor_logs')
    op.drop_table('vehicle_logs')
    op.drop_index('ix_security_incidents_property', table_name='security_incidents')
    op.drop_table('security_incidents')
    op.drop_table('property_incident_reports')
    op.drop_index('ix_pricing_rules_property_active', table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_device_blacklist_device_uid'), table_name='device_blacklist')
    op.drop_table('device_blacklist')
    op.drop_table('commission_payouts')
    op.drop_table('broker_wallets')
    op.drop_table('broker_commission_rules')
    # ### end Alembic commands ###
