"""Add tasks models

Revision ID: d9426f4327a3
Revises: 6c73c256b2d2
Create Date: 2026-07-17 14:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9426f4327a3'
down_revision: Union[str, None] = '6c73c256b2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'tasks' in inspector.get_table_names(schema='public'):
        print("Tasks table already exists, skipping add_tasks_models migration.")
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('room_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('booking_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('assigned_to', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['public.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['public.bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['public.rooms.room_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    schema='public'
    )
    
    op.create_table('task_logs',
    sa.Column('log_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['public.tasks.task_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_logs', schema='public')
    op.drop_table('tasks', schema='public')
    # ### end Alembic commands ###
